var child = [
  { 'dupe': false, 'type': 8, 'name': 'all', 'dir': 'c0', 'linked': 2, 'url': 'http://127.0.0.1:8000/bank/przelew/all', 'fetched': true, 'code': 302, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': false, 'type': 64, 'name': 'csrfmiddlewaretoken=5Q0KT1jUlAAmW6iyVnmG05eneSNrYFOo4GvHEBDC32pBSRh6mogBl4kOCUKQ3bvF', 'dir': 'c1', 'linked': 5, 'url': 'http://127.0.0.1:8000/bank/przelew DATA:csrfmiddlewaretoken=5Q0KT1jUlAAmW6iyVnmG05eneSNrYFOo4GvHEBDC32pBSRh6mogBl4kOCUKQ3bvF&odbiorca=1&rachunek=1&kwota=1&data=1&tytul=1', 'fetched': true, 'code': 403, 'len': 2513, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xffbed75f },
  { 'dupe': false, 'type': 64, 'name': 'data=1', 'dir': 'c2', 'linked': 5, 'url': 'http://127.0.0.1:8000/bank/przelew DATA:csrfmiddlewaretoken=5Q0KT1jUlAAmW6iyVnmG05eneSNrYFOo4GvHEBDC32pBSRh6mogBl4kOCUKQ3bvF&odbiorca=1&rachunek=1&kwota=1&data=1&tytul=1', 'fetched': true, 'code': 403, 'len': 2513, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xffbed75f },
  { 'dupe': false, 'type': 64, 'name': 'kwota=1', 'dir': 'c3', 'linked': 5, 'url': 'http://127.0.0.1:8000/bank/przelew DATA:csrfmiddlewaretoken=5Q0KT1jUlAAmW6iyVnmG05eneSNrYFOo4GvHEBDC32pBSRh6mogBl4kOCUKQ3bvF&odbiorca=1&rachunek=1&kwota=1&data=1&tytul=1', 'fetched': true, 'code': 403, 'len': 2513, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xffbed75f },
  { 'dupe': false, 'type': 64, 'name': 'odbiorca=1', 'dir': 'c4', 'linked': 5, 'url': 'http://127.0.0.1:8000/bank/przelew DATA:csrfmiddlewaretoken=5Q0KT1jUlAAmW6iyVnmG05eneSNrYFOo4GvHEBDC32pBSRh6mogBl4kOCUKQ3bvF&odbiorca=1&rachunek=1&kwota=1&data=1&tytul=1', 'fetched': true, 'code': 403, 'len': 2513, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xffbed75f },
  { 'dupe': false, 'type': 64, 'name': 'rachunek=1', 'dir': 'c5', 'linked': 5, 'url': 'http://127.0.0.1:8000/bank/przelew DATA:csrfmiddlewaretoken=5Q0KT1jUlAAmW6iyVnmG05eneSNrYFOo4GvHEBDC32pBSRh6mogBl4kOCUKQ3bvF&odbiorca=1&rachunek=1&kwota=1&data=1&tytul=1', 'fetched': true, 'code': 403, 'len': 2513, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xffbed75f },
  { 'dupe': false, 'type': 64, 'name': 'tytul=1', 'dir': 'c6', 'linked': 5, 'url': 'http://127.0.0.1:8000/bank/przelew DATA:csrfmiddlewaretoken=5Q0KT1jUlAAmW6iyVnmG05eneSNrYFOo4GvHEBDC32pBSRh6mogBl4kOCUKQ3bvF&odbiorca=1&rachunek=1&kwota=1&data=1&tytul=1', 'fetched': true, 'code': 403, 'len': 2513, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xffbed75f }
];
