var child = [
  { 'dupe': false, 'type': 4, 'name': 'admin', 'dir': 'c0', 'linked': 5, 'url': 'http://127.0.0.1:8000/admin/', 'fetched': true, 'code': 302, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': false, 'csens': true, 'child_cnt': 9, 'issue_cnt': [ 6, 0, 0, 0, 0 ], 'sig': 0x556082c0 },
  { 'dupe': false, 'type': 4, 'name': 'bank', 'dir': 'c1', 'linked': 5, 'url': 'http://127.0.0.1:8000/bank/', 'fetched': true, 'code': 200, 'len': 189, 'decl_mime': 'text/html', 'sniff_mime': 'text/html', 'cset': 'utf-8', 'missing': false, 'csens': true, 'child_cnt': 16, 'issue_cnt': [ 6, 2, 1, 0, 0 ], 'sig': 0xab22cbe6 },
  { 'dupe': false, 'type': 4, 'name': 'bank', 'dir': 'c2', 'linked': 2, 'url': 'http://127.0.0.1:8000/bank/', 'fetched': true, 'code': 200, 'len': 138, 'decl_mime': 'text/html', 'sniff_mime': 'text/html', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xfffad823 },
  { 'dupe': false, 'type': 4, 'name': 'login', 'dir': 'c5', 'linked': 5, 'url': 'http://127.0.0.1:8000/login/', 'fetched': true, 'code': 200, 'len': 646, 'decl_mime': 'text/html', 'sniff_mime': 'text/html', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 4, 'issue_cnt': [ 2, 0, 0, 0, 0 ], 'sig': 0x3fd2ac8 },
  { 'dupe': false, 'type': 4, 'name': 'logout', 'dir': 'c6', 'linked': 0, 'url': 'http://127.0.0.1:8000/logout/', 'fetched': true, 'code': 200, 'len': 1207, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfffbffff },
  { 'dupe': false, 'type': 4, 'name': 'password_reset', 'dir': 'c7', 'linked': 5, 'url': 'http://127.0.0.1:8000/password_reset/', 'fetched': true, 'code': 200, 'len': 1742, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': true, 'child_cnt': 3, 'issue_cnt': [ 0, 0, 1, 0, 0 ], 'sig': 0xc236fa6c },
  { 'dupe': false, 'type': 4, 'name': 'static', 'dir': 'c8', 'linked': 2, 'url': 'http://127.0.0.1:8000/static/', 'fetched': true, 'code': 404, 'len': 1634, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 6, 'issue_cnt': [ 18, 0, 0, 0, 0 ], 'sig': 0xbbb80962 }
];
